# Generated by Django 4.0.2 on 2022-02-13 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام کارمند')),
                ('last_name', models.CharField(max_length=200, verbose_name='تخلص کارمند')),
                ('father_name', models.CharField(max_length=200, verbose_name='نام پدر')),
                ('position', models.CharField(max_length=200, verbose_name='وظیفه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس کارمند')),
                ('salary', models.IntegerField(default=0, verbose_name='معاش کارمند')),
                ('head', models.BooleanField(default=False, verbose_name='سرگروپ')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح پرداخت')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='میزان دستمزد')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مجموع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار پرداخت شده')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار باقی مانده')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='نام مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب')], default='حاضر', max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2022, 2, 13, 14, 22, 59, 886749, tzinfo=utc))),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
