# Generated by Django 4.0.2 on 2022-04-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام کارمند')),
                ('last_name', models.CharField(max_length=200, verbose_name='تخلص کارمند')),
                ('father_name', models.CharField(max_length=200, verbose_name='نام پدر')),
                ('position', models.CharField(max_length=200, verbose_name='وظیفه')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس کارمند')),
                ('salary', models.IntegerField(default=0, verbose_name='معاش کارمند')),
                ('head', models.BooleanField(default=False, verbose_name='سرگروپ')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(choices=[('حاضر', 'حاضر'), ('غایب', 'غایب')], default='حاضر', max_length=20)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
