# Generated by Django 4.0.2 on 2022-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeattendance_date_delete_employeepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
