# Generated by Django 4.0.2 on 2022-04-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مشتری')),
                ('last_name', models.CharField(max_length=200, verbose_name='تخلص مشتری')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس مشتری')),
                ('social_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس مشتری')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FinanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='مقدار به حروف')),
                ('pay_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداخت شد')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان واقعه')),
                ('event_finish_at', models.DateTimeField(verbose_name='تاریخ ختم فرصت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
