# Generated by Django 4.0.2 on 2022-02-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مشتری')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس مشتری')),
                ('social_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ')),
                ('address', models.TextField(verbose_name='آدرس مشتری')),
            ],
        ),
    ]
