# Generated by Django 4.0.2 on 2022-03-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('داد', 'داد'), ('گرفت', 'گرفت')], default='داد', max_length=50)),
                ('total_pre_loan', models.PositiveIntegerField(default=0, verbose_name='مجموع باقی مانده های قبلی')),
                ('pay_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شد')),
                ('remain', models.PositiveIntegerField(default=0, verbose_name='مقدار باقی مانده')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان واقعه')),
                ('event_finish_at', models.DateTimeField(verbose_name='تاریخ ختم فرصت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
