# Generated by Django 4.0.2 on 2022-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_financedetail_customerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevent',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerevent',
            name='event_finish_at',
            field=models.DateField(verbose_name='تاریخ ختم فرصت'),
        ),
    ]
