# Generated by Django 4.0.2 on 2022-03-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerevent_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedetail',
            name='total_remain',
            field=models.PositiveIntegerField(default=0, verbose_name=''),
        ),
    ]
