# Generated by Django 4.0.2 on 2022-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_financedetail_total_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedetail',
            name='pay_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ پرداخت شد'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='remain',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار باقی مانده'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='total_pre_loan',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مجموع باقی مانده های قبلی'),
        ),
    ]
