# Generated by Django 4.0.2 on 2022-02-13 14:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('دروازه', 'دروازه'), ('کلکین', 'کلکین'), ('سی ان سی', 'سی ان سی'), ('پرس', 'پرس'), ('ضد سرقت', 'ضد سرفت')], max_length=50, verbose_name='خدمات')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قد')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='بر')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عمق')),
                ('direction', models.CharField(choices=[('راست', 'راست'), ('چپ', 'چپ')], default='راست', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مقدار / تعداد')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='قیمت فی واحد')),
                ('paid', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='مقدار رسید')),
                ('remain', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='مقدار باقی مانده')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='مجموع پول')),
                ('order_date', django_jalali.db.models.jDateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
