# Generated by Django 4.0.2 on 2022-02-13 16:16

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeattendance_date_delete_employeepay'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ فرمایش'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح پرداخت')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='میزان دستمزد')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مجموع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار پرداخت شده')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار باقی مانده')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='نام مشتری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
