# Generated by Django 4.0.2 on 2022-04-04 11:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح پرداخت')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مقدار / تعداد')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='قیمت فی واحد')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مجموع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار پرداخت شده')),
                ('remain_amount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='مقدار باقی مانده')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remain',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
