# Generated by Django 4.0.2 on 2022-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_remove_order_paid_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار پرداخت شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='قیمت فی واحد'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='مقدار / تعداد'),
        ),
        migrations.AddField(
            model_name='order',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مقدار باقی مانده'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مجموع'),
        ),
    ]
