# Generated by Django 4.0.2 on 2022-02-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='نوعیت کار'),
            preserve_default=False,
        ),
    ]
