# Generated by Django 4.0.2 on 2022-03-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_type_order_worktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='workType',
            new_name='type',
        ),
    ]
